apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      imagePullSecrets:          #docker hub 관련 정보 추가
      - name: dockerhub-secret #docker hub 관련 정보 추가
      containers:
      - name: my-webserver
        image: fhwang98/echo-hostname:4c79fef08bfb0e589b72dcad55ad91079926f3f7
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
